[config]
schemaVersion = "0.0.1"

[package]
namespace = "jakobhellermann"
description = "Utilities for practicing speedruns"

websiteUrl = "https://github.com/jakobhellermann/SpeedrunGym"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Silksong = "5.4.2304"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./dist"

[[build.copy]]
source = "./temp"
target = "/"

# additional files and directories can be added to the package like this:
# [[build.copy]]
# source = "./CHANGELOG.md"
# target = "/"

[publish]
repository = "https://thunderstore.io"
communities = [ "hollow-knight-silksong" ]

[publish.categories]
# available categories can be found at https://github.com/thunderstore-io/ecosystem-schema/blob/master/games/data/hollow-knight-silksong.yml
hollow-knight-silksong = [ "mods", "utility" ]
